version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gate_keeper_local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306
    networks: 
      - app-net
  api:
    container_name: gatekeeper-backend
    build:
      context: .
      dockerfile: DockerfileDev
    restart: always
    volumes:
      - .:/app/
    ports:
      - 5000:8000
    environment: 
      - DB_HOST=db
      - DB_USER=local
      - DB_PASS=local
      - DB_NAME=gate_keeper_local
    networks: 
      - app-net
  # nginx:
  #   container_name: nginx 
  #   build:
  #     context: .
  #     dockerfile: NginxDockerfile
  #   restart: always
  #   ports:
  #     - 3333:80
  #   networks: 
  #     - app-net
networks:
  app-net:
    driver: bridge