version: '3.7'

services:
  gunicorn:
    image: gatekeeper-backend:tmp 
    container_name: gatekeeper-backend
    volumes:
      - .:/app/
      - gunicorn:/var/run/gunicorn
  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on: 
      - gunicorn
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
      - ./log:/var/log/nginx/

volumes:
  gunicorn:
    driver: local