version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gate_keeper_local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    # - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  gunicorn:
    image: gatekeeper-backend:tmp 
    container_name: gatekeeper-backend
    volumes:
      - .:/app/
      - gunicorn:/var/run/gunicorn
  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on: 
      - gunicorn
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
      - ./log:/var/log/nginx/

volumes:
  gunicorn:
    driver: local