version: 1

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /tmp/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: INFO
    handlers: [console]
    propogate: yes

loggers:
    backend:
        level: INFO
        handlers: [console]
        propogate: no
    fastapi:
        level: DEBUG 
        handlers: [console]
        propogate: no
    uvicorn:
        level: DEBUG 
        handlers: [console]
        propogate: no

    